apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    metadata:
      name: hello-world-pod
    spec:
      containers:
      - name: hello-world
        image: 127.0.0.1:5000/practicaldevopsguy/hello_world_multi_node:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Never